name: CI - Testes e Cobertura de Código

on: ["push", "pull_request"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [8.3]
        test_number: [1, 2]  # Adicionando a matriz para paralelismo
    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3  # Atualize para a versão correta

      # Configurar a versão do PHP
      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug  # Para habilitar a cobertura de código

      # Instalar dependências do Composer
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # Rodar os testes em paralelo
      - name: Run test suite ${{ matrix.test_number }}
        run: composer run-script test-coverage-${{ matrix.test_number }}

      # Enviar cobertura ao Coveralls
      - name: Upload to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          flag-name: run-${{ join(matrix.test_number, '-') }}  # Para identificar a execução
          parallel: true

  finish:
    needs: test
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      # Finalizar envio ao Coveralls
      - name: Finalize Coveralls
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
          carryforward: "run-1,run-2"  # Identificando as execuções paralelas
